/** Design tokens — sync with stitch velvet_paws_narrative / DESIGN.md */
export const colors = {
  background: '#fdf9f0',
  onBackground: '#1c1c17',
  surface: '#fdf9f0',
  surfaceDim: '#dddad1',
  surfaceBright: '#fdf9f0',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f7f3ea',
  surfaceContainer: '#f1eee5',
  surfaceContainerHigh: '#ece8df',
  surfaceContainerHighest: '#e6e2d9',
  surfaceVariant: '#e6e2d9',
  onSurface: '#1c1c17',
  onSurfaceVariant: '#504441',
  inverseSurface: '#31312b',
  inverseOnSurface: '#f4f0e8',
  outline: '#827470',
  outlineVariant: '#d4c3be',
  surfaceTint: '#77574d',
  primary: '#442a22',
  onPrimary: '#ffffff',
  primaryContainer: '#5d4037',
  onPrimaryContainer: '#d4ada1',
  inversePrimary: '#e7bdb1',
  primaryFixed: '#ffdbd0',
  primaryFixedDim: '#e7bdb1',
  onPrimaryFixed: '#2c160e',
  onPrimaryFixedVariant: '#5d4037',
  secondary: '#735c00',
  onSecondary: '#ffffff',
  secondaryContainer: '#fed65b',
  onSecondaryContainer: '#745c00',
  secondaryFixed: '#ffe088',
  secondaryFixedDim: '#e9c349',
  onSecondaryFixed: '#241a00',
  onSecondaryFixedVariant: '#574500',
  tertiary: '#2e3222',
  onTertiary: '#ffffff',
  tertiaryContainer: '#444937',
  onTertiaryContainer: '#b3b8a1',
  tertiaryFixed: '#e0e5cc',
  tertiaryFixedDim: '#c4c9b1',
  onTertiaryFixed: '#191d0e',
  onTertiaryFixedVariant: '#444937',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
} as const

export type ThemeColor = keyof typeof colors
